---
- name: Pull docker image from dockerhub
  hosts: all
  tasks:
    - name: Pull docker image
      docker_image:
        name: statstop/statstop_frontend
        source: pull
    - name: Remove already created container
      shell: docker rm statstop_frontend
    - name: create and run container
      shell: docker run -it --name statstop_frontend statstop/statstop_frontend
    