---
- name: Pull docker image from dockerhub
  hosts: all
  tasks:
    - name: Pull docker image
      docker_image:
        name: statstop/statstop_frontend
        source: pull
        
    # - name: remove if a container already exists
    #   shell: |
    #     if  [[ "$(docker ps -a | grep frontend_container | wc -l)" > "0" ]]; then
    #       echo $(docker rm -f frontend_container)
    #     fi

    # - name: create and run container
    #   shell: docker run -d -p 3000:3000 --name frontend_container statstop/statstop_frontend
    - name: Stop and remove existing container
      docker_container:
        name: frontend_container
        state: absent

    - name: create and run container
      docker_container:
        name: frontend_container
        image: statstop/statstop_frontend
        ports:
          - "3000:3000"
        detach: true
    